In [2722]:
import math
import numpy as np
# Note: please don't add any new package, you should solve this problem using only the packages above.
#-------------------------------------------------------------------------
'''
    Problem 1: Linear Regression
    In this problem, you will implement the linear regression method based upon gradient descent.
    Xw  = y
    You could test the correctness of your code by typing `pytest -v test.py` in the terminal.
    Note: please don't use any existing package for linear regression problem, implement your own version.
'''

#--------------------------
def compute_Phi(x,p):
    '''
        Compute the feature matrix Phi of x. We will construct p polynoials, the p features of the data samples. 
        The features of each sample, is x^0, x^1, x^2 ... x^(p-1)
        Input:
            x : a vector of samples in one dimensional space, a numpy vector of shape (n,).
                Here n is the number of samples.
            p : the number of polynomials/features
        Output:
            Phi: the design/feature matrix of x, a numpy array of shape (n,p).
    '''
    #########################################
    ## INSERT YOUR CODE HERE
    #phi1(x) + phi2(x).....phid(x)
    #h w (x) = w 0 + w 1 * phi1(x1) + w 2 * phi2(x2) + ... + w d * phid(xd)
    columns = []
    for i in range(p):
        column = x**i
        columns.append(column)
    Phi = np.column_stack(columns)
    


    #########################################
    return Phi 

#--------------------------
def compute_yhat(Phi, w):
    '''
        Compute the linear logit value (predicted value) of all data instances. z = <w, x>
        Here <w, x> represents the dot product of the two vectors.
        Input:
            Phi: the feature matrix of all data instance, a float numpy array of shape (n,p). 
            w: the weights parameter of the linear model, a float numpy array of shape (p,). 
        Output:
            yhat: the logit value (predicted value) of all instances, a float numpy array of shape (n,)
        Hint: you could solve this problem using 1 line of code. Though using more lines of code is also okay.
    '''
    #########################################
    ## INSERT YOUR CODE HERE
    # y hat or ŷ = h w (x) = w 0 + w 1 * phi1(x1) + w 2 * phi2(x2) + ... + w d * phid(xd)
    yhat = Phi.dot(w)

    #########################################

    return yhat

    #--------------------------
def compute_L(yhat,y):
    '''
        Compute the loss function: mean squared error. In this function, divide the original mean squared error by 2 for making gradient computation simple. Remember our loss function in the slides.  
        Input:
            yhat: the predicted sample labels, a numpy vector of shape (n,).
            y:  the sample labels, a numpy vector of shape (n,).
        Output:
            L: the loss value of linear regression, a float scalar.
    '''
    #########################################
    ## INSERT YOUR CODE HERE
    # L = J(theta or w) = (1/2n) * (((ŷ1 - y1) + (ŷ2 - y2) + ... (ŷn - yn))^2) 
    
    L = np.mean((yhat-y)**2)/2

    #########################################
    return L 



def compute_dL_dw(y, yhat, Phi):
    '''
        Compute the gradients of the loss function L with respect to (w.r.t.) the weights w. 
        Input:
            Phi: the feature matrix of all data instances, a float numpy array of shape (n,p). 
               Here p is the number of features/dimensions.
            y: the sample labels, a numpy vector of shape (n,).
            yhat: the predicted sample labels, a numpy vector of shape (n,).
        Output:
            dL_dw: the gradients of the loss function L with respect to the weights w, a numpy float array of shape (p,). 

    '''
    #########################################
    ## INSERT YOUR CODE HERE
    # dl/dw = dJ(ŷ)/dw = (1/n) * ((((ŷ1(1)- y1(1)) + (ŷ2(1) - y2(1)) + ... (ŷd(1) - yd(1))) * xw1 +
    #                              +   (ŷ1(2)- y1(2)) + (ŷ2(2) - y2(2)) + ... (ŷd(2) - yd(2))) * xw2 + ... 
    #                              + (((ŷ1(n) - y1(n)) + (ŷ2(n) - y2(n)) + ... (ŷd(n) - yd(n))) * xwn
    n = len(y)
    dL_dw = (1/n)*Phi.T.dot(yhat - y)

    #########################################
    return dL_dw


#--------------------------
def update_w(w, dL_dw, alpha = 0.001):
    '''
       Given the instances in the training data, update the weights w using gradient descent.
        Input:
            w: the current value of the weight vector, a numpy float array of shape (p,).
            dL_dw: the gradient of the loss function w.r.t. the weight vector, a numpy float array of shape (p,). 
            alpha: the step-size parameter of gradient descent, a float scalar.
        Output:
            w: the updated weight vector, a numpy float array of shape (p,).
        Hint: you could solve this problem using 1 line of code
    '''
    
    #########################################
    ## INSERT YOUR CODE HERE
    # w[j] := w[j] - alpha * dL_dw 
    
    w = w - (alpha*dL_dw)

    #########################################
    return w


#--------------------------
def train(X, Y, alpha=0.001, n_epoch=100):  
    '''
       Given a training dataset, train the linear regression model by iteratively updating the weights w using the gradient descent
        We repeat n_epoch passes over all the training instances.
        Input:
            X: the feature matrix of training instances, a float numpy array of shape (n, p). Here n is the number of data instance in the training set, p is the number of features/dimensions.
            Y: the labels of training instance, a numpy integer array of shape (n,). 
            alpha: the step-size parameter of gradient descent, a float scalar.
            n_epoch: the number of passes to go through the training set, an integer scalar.
        Output:
            w: the weight vector trained on the training set, a numpy float array of shape (p,). 
    '''

    # initialize weights as 0
    w = np.array(np.zeros(X.shape[1])).T

    for _ in range(n_epoch):

    #########################################
    ## INSERT YOUR CODE HERE

    # Back propagation: compute local gradients 

        yhat = compute_yhat(X, w)
        dL_dw = compute_dL_dw(Y, yhat, X)
        
        
    # update the parameters w
        w = update_w(w, dL_dw, alpha)

    #########################################
    return w

In [957]:
###Testing on the go
import numpy as np
x=np.array([1,2,3,4])
p=3
Phi = np.column_stack([x**i for i in range(p)])
print(Phi)

print('Trying it the other way')
columns = []
for i in range(p):
    column = x**i
    columns.append(column)
    print(i)
    print(f'column: {column}')
    print(f'columns: {columns}')
Phi2 = np.column_stack(columns)
print(Phi2)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
Trying it the other way
0
column: [1 1 1 1]
columns: [array([1, 1, 1, 1])]
1
column: [1 2 3 4]
columns: [array([1, 1, 1, 1]), array([1, 2, 3, 4])]
2
column: [ 1  4  9 16]
columns: [array([1, 1, 1, 1]), array([1, 2, 3, 4]), array([ 1,  4,  9, 16])]
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]


In [958]:
w = np.array([19,6,7])
yhat = Phi2.dot(w)
print(yhat)

[ 32  59 100 155]


In [959]:
y = np.array([190, 46, 87, 142])
L = np.mean((yhat-y)**2)/2
print(L)

3183.875


In [960]:
n = len(y)
dL_dw = (1/n)*Phi.T.dot(yhat - y)
print(dL_dw)

[-29.75 -10.25  54.75]


In [2653]:
alpha = 0.1
w = w - (alpha*dL_dw)
print(w)

[115.72984738  -8.87047413   2.37515961]


In [2694]:
yhat = Phi2.dot(w)
print(yhat)
dL_dw = (1/n)*Phi.T.dot(yhat - y)
print(dL_dw)
w = w - (alpha*dL_dw)
print(w)
L = np.mean((yhat-y)**2)/2
print(L)

[-9.63692766e+22 -3.27329037e+23 -6.98941251e+23 -1.21120592e+24]
[-5.83461371e+23 -1.92316869e+24 -6.76886285e+24]
[5.22841681e+22 1.72335788e+23 6.06560058e+23]
2.58996248203771e+47


In [2721]:
print(yhat)
print(y)

[-9.63692766e+22 -3.27329037e+23 -6.98941251e+23 -1.21120592e+24]
[190  46  87 142]
